title: Arvind Kumar Bhartia
tagline: "Think like an artist. Always creative."
version:
permalink: /:categories/:title/
baseurl: ""
repository:
  web: "arvindbhartia.github.io"
  git: "git:////github.com/arvindbhartia/arvindbhartia.github.io"
google:
  search: ""
  analytics: ""
  plus: ""
highlight_libraries:
  - comp_1
  - comp_2
  - comp_3
  - comp_4
  - comp_5
  - comp_6
  - comp_7
  - comp_8
  - comp_9
  - comp_11
  - comp_12
  - comp_13
  - comp_14
  - comp_15
  - comp_16
exclude:
  - "Gruntfile.coffee"
  - "README.md"
  - "package.json"
